# License: OPL-1 (https://www.odoo.com/documentation/17.0/legal/licenses.html)
from . import uva_api_client
from . import uva_api_retry_queue
from . import uva_store_config
from . import uva_product_mapping
from . import res_config_settings
from . import uva_order_log
from . import uva_order_service
from . import uva_fleet_delivery
from . import delivery_uva
from . import uva_fleet_estimate_wizard
from . import uva_fleet_service
