# License: OPL-1 (https://www.odoo.com/documentation/18.0/legal/licenses.html)
# uva_api_client must be first — other modules import its exceptions
from . import uva_api_client
from . import delivery_uva
from . import pos_order
from . import res_config_settings
from . import sale_order
from . import uva_api_retry_queue
from . import uva_bulk_mapping_wizard
from . import uva_fleet_delivery
from . import uva_fleet_estimate_wizard
from . import uva_fleet_service
from . import uva_menu_sync
from . import uva_notification
from . import uva_order_log
from . import uva_order_rule
from . import uva_order_service
from . import uva_product_alias
from . import uva_product_mapping
from . import uva_setup_wizard
from . import uva_store_config
